HOME_PATH: ${oc.env:GENALM_HOME}
output_dir: ${HOME_PATH}/runs/regression/modernGENA/

batch_size: 8
total_batch_size: 64

# --- MODEL ---
model:
  _target_: "downstream_tasks.phageml.regressor_multigpu.annotation_model.AnnotationModel"
  output_dir: ${output_dir}
  config: null  # Path to the BERT configuration file; null will load from huggingface
  modernbert_cpt: "downstream_tasks/phageml/ckpt/base_metavr_bpe_continue/"
  pretrained_cpt: null
  backbone_dropout:
    mlp_dropout_prob: 0.01

  classifier:
    _target_: "downstream_tasks.phageml.regressor_multigpu.annotation_model.Linear_Classifier_with_dropout"
    num_labels: 1
    num_layers: 1  # Number of layers
    classifier_dropout: 0.0  # Dropout rate

  activation:
    _target_: "torch.nn.Identity"

  # Loss-fct: nn.MSELoss + CLS-pooling
  loss_fct:
    _target_: "downstream_tasks.phageml.regressor_multigpu.regression_loss.CLSMSELossDict"
    cls_pos: 0


# --- DATASETS ---

train_dataset:
  _target_: "downstream_tasks.phageml.regressor_multigpu.simple_test_dataset.RegressionScoringDataset"
  max_length: 1024
  data_path: "downstream_tasks/phageml/datasets/simple_test/train_v2_positive.hdf5"
  tokenizer:
    _target_: "transformers.AutoTokenizer.from_pretrained"
    pretrained_model_name_or_path: "AIRI-Institute/gena-lm-bert-base-t2t"

valid_dataset:
  _target_: "downstream_tasks.phageml.regressor_multigpu.simple_test_dataset.RegressionScoringDataset"
  max_length: 1024
  data_path: "downstream_tasks/phageml/datasets/simple_test/test_v2_positive.hdf5"
  tokenizer:
    _target_: "transformers.AutoTokenizer.from_pretrained"
    pretrained_model_name_or_path: "AIRI-Institute/gena-lm-bert-base-t2t"


# --- HF TrainingArguments ---
TrainingArguments:
  _target_: transformers.TrainingArguments
  output_dir: ${output_dir}

  per_device_train_batch_size: ${batch_size}
  per_device_eval_batch_size: ${batch_size}

  gradient_accumulation_steps:
    _target_: downstream_tasks.phageml.regressor_multigpu.train_with_accelerate_multigpu.gradient_accumulation_steps
    batch_size: ${batch_size}
    total_batch_size: ${total_batch_size}

  dataloader_num_workers: 4
  dataloader_pin_memory: false
  remove_unused_columns: false

  # eval/checkpoints
  load_best_model_at_end: true
  metric_for_best_model: "eval_valid_loss"
  eval_strategy: "epoch"
  save_strategy: "best"
  #save_steps: 11780
  #eval_steps: 1178
  save_total_limit: 2

  # optimization
  num_train_epochs: 700
  learning_rate: 1e-6
  weight_decay: 0.01
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.05

  # tensorboard
  report_to: "tensorboard"
  logging_steps: 50
  logging_dir: ${output_dir}/tb


# --- TRAINER ---
trainer:
  _target_: downstream_tasks.phageml.regressor_multigpu.custom_trainer.CustomTrainerWeightedBalancedBins
  model: ${model}

  data_collator:
    _target_: hydra.utils.get_object
    path: transformers.default_data_collator

  train_dataset: ${train_dataset}
  eval_dataset:
    valid: ${valid_dataset}
    train: ${train_dataset}
  args: ${TrainingArguments}

  weighted_sampling:
    mode: balanced_bins
    bins_edges: [0.2, 0.3, 0.4, 0.5, 0.6]
    empty_bin_policy: skip

  log_train_metrics: 50
  train_metrics:
    - _target_: downstream_tasks.phageml.regressor_multigpu.custom_trainer.NamedMean
      cls_name: "loss"

  compute_metrics:
    _target_: hydra.utils.get_object
    path: downstream_tasks.phageml.regressor_multigpu.regression_loss.compute_regression_metrics

  callbacks:
    - _target_: downstream_tasks.phageml.regressor_multigpu.custom_trainer.SaveEveryNEpochsCallback
      every_n_epochs: 50
      extra_dir: "periodic"  